// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFUJ8UbaTS1LM-xUFUNJo9Q67v1_wFTw',
    appId: '1:898217032810:web:0e3097deaf62d03622de13',
    messagingSenderId: '898217032810',
    projectId: 'vigilance-659a3',
    authDomain: 'vigilance-659a3.firebaseapp.com',
    storageBucket: 'vigilance-659a3.appspot.com',
    measurementId: 'G-SCM6KN6DJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgJuED2A1FPYlF6kViN4cZAoq49DcwM8U',
    appId: '1:898217032810:android:514844525045127322de13',
    messagingSenderId: '898217032810',
    projectId: 'vigilance-659a3',
    storageBucket: 'vigilance-659a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUd16kmKA2Ik_3UDQlHMCEz0IcSvXc1rQ',
    appId: '1:898217032810:ios:08b480b66a7af5d122de13',
    messagingSenderId: '898217032810',
    projectId: 'vigilance-659a3',
    storageBucket: 'vigilance-659a3.appspot.com',
    iosBundleId: 'com.vig.vig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUd16kmKA2Ik_3UDQlHMCEz0IcSvXc1rQ',
    appId: '1:898217032810:ios:8ae5679bf59d2c5122de13',
    messagingSenderId: '898217032810',
    projectId: 'vigilance-659a3',
    storageBucket: 'vigilance-659a3.appspot.com',
    iosBundleId: 'com.vig.vig.RunnerTests',
  );
}
